// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: Define/BattleMsg.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Network {

  /// <summary>Holder for reflection information generated from Define/BattleMsg.proto</summary>
  public static partial class BattleMsgReflection {

    #region Descriptor
    /// <summary>File descriptor for Define/BattleMsg.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static BattleMsgReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChZEZWZpbmUvQmF0dGxlTXNnLnByb3RvEgdOZXR3b3JrIqoBChBiYXR0bGVf",
            "c3RhcnRfczJjEhAKCHNlbGZfdWlkGAEgASgFEjYKB3BsYXllcnMYAiADKAsy",
            "JS5OZXR3b3JrLmJhdHRsZV9zdGFydF9zMmMucGxheWVyX2luZm8aTAoLcGxh",
            "eWVyX2luZm8SCwoDdWlkGAEgASgFEhMKC2NoYW1waW9uX2lkGAIgASgFEgwK",
            "BGNhbXAYAyABKAUSDQoFc2tpbGwYBCADKAViBnByb3RvMw=="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Network.battle_start_s2c), global::Network.battle_start_s2c.Parser, new[]{ "SelfUid", "Players" }, null, null, new pbr::GeneratedClrTypeInfo[] { new pbr::GeneratedClrTypeInfo(typeof(global::Network.battle_start_s2c.Types.player_info), global::Network.battle_start_s2c.Types.player_info.Parser, new[]{ "Uid", "ChampionId", "Camp", "Skill" }, null, null, null)})
          }));
    }
    #endregion

  }
  #region Messages
  /// <summary>
  /// 战斗开始
  /// </summary>
  public sealed partial class battle_start_s2c : pb::IMessage<battle_start_s2c> {
    private static readonly pb::MessageParser<battle_start_s2c> _parser = new pb::MessageParser<battle_start_s2c>(() => new battle_start_s2c());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<battle_start_s2c> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Network.BattleMsgReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public battle_start_s2c() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public battle_start_s2c(battle_start_s2c other) : this() {
      selfUid_ = other.selfUid_;
      players_ = other.players_.Clone();
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public battle_start_s2c Clone() {
      return new battle_start_s2c(this);
    }

    /// <summary>Field number for the "self_uid" field.</summary>
    public const int SelfUidFieldNumber = 1;
    private int selfUid_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int SelfUid {
      get { return selfUid_; }
      set {
        selfUid_ = value;
      }
    }

    /// <summary>Field number for the "players" field.</summary>
    public const int PlayersFieldNumber = 2;
    private static readonly pb::FieldCodec<global::Network.battle_start_s2c.Types.player_info> _repeated_players_codec
        = pb::FieldCodec.ForMessage(18, global::Network.battle_start_s2c.Types.player_info.Parser);
    private readonly pbc::RepeatedField<global::Network.battle_start_s2c.Types.player_info> players_ = new pbc::RepeatedField<global::Network.battle_start_s2c.Types.player_info>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::RepeatedField<global::Network.battle_start_s2c.Types.player_info> Players {
      get { return players_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as battle_start_s2c);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(battle_start_s2c other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (SelfUid != other.SelfUid) return false;
      if(!players_.Equals(other.players_)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (SelfUid != 0) hash ^= SelfUid.GetHashCode();
      hash ^= players_.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (SelfUid != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(SelfUid);
      }
      players_.WriteTo(output, _repeated_players_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (SelfUid != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(SelfUid);
      }
      size += players_.CalculateSize(_repeated_players_codec);
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(battle_start_s2c other) {
      if (other == null) {
        return;
      }
      if (other.SelfUid != 0) {
        SelfUid = other.SelfUid;
      }
      players_.Add(other.players_);
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            SelfUid = input.ReadInt32();
            break;
          }
          case 18: {
            players_.AddEntriesFrom(input, _repeated_players_codec);
            break;
          }
        }
      }
    }

    #region Nested types
    /// <summary>Container for nested types declared in the battle_start_s2c message type.</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static partial class Types {
      public sealed partial class player_info : pb::IMessage<player_info> {
        private static readonly pb::MessageParser<player_info> _parser = new pb::MessageParser<player_info>(() => new player_info());
        private pb::UnknownFieldSet _unknownFields;
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public static pb::MessageParser<player_info> Parser { get { return _parser; } }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public static pbr::MessageDescriptor Descriptor {
          get { return global::Network.battle_start_s2c.Descriptor.NestedTypes[0]; }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        pbr::MessageDescriptor pb::IMessage.Descriptor {
          get { return Descriptor; }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public player_info() {
          OnConstruction();
        }

        partial void OnConstruction();

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public player_info(player_info other) : this() {
          uid_ = other.uid_;
          championId_ = other.championId_;
          camp_ = other.camp_;
          skill_ = other.skill_.Clone();
          _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public player_info Clone() {
          return new player_info(this);
        }

        /// <summary>Field number for the "uid" field.</summary>
        public const int UidFieldNumber = 1;
        private int uid_;
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public int Uid {
          get { return uid_; }
          set {
            uid_ = value;
          }
        }

        /// <summary>Field number for the "champion_id" field.</summary>
        public const int ChampionIdFieldNumber = 2;
        private int championId_;
        /// <summary>
        /// 英雄
        /// </summary>
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public int ChampionId {
          get { return championId_; }
          set {
            championId_ = value;
          }
        }

        /// <summary>Field number for the "camp" field.</summary>
        public const int CampFieldNumber = 3;
        private int camp_;
        /// <summary>
        /// 阵营
        /// </summary>
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public int Camp {
          get { return camp_; }
          set {
            camp_ = value;
          }
        }

        /// <summary>Field number for the "skill" field.</summary>
        public const int SkillFieldNumber = 4;
        private static readonly pb::FieldCodec<int> _repeated_skill_codec
            = pb::FieldCodec.ForInt32(34);
        private readonly pbc::RepeatedField<int> skill_ = new pbc::RepeatedField<int>();
        /// <summary>
        /// 召唤师技能
        /// </summary>
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public pbc::RepeatedField<int> Skill {
          get { return skill_; }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public override bool Equals(object other) {
          return Equals(other as player_info);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public bool Equals(player_info other) {
          if (ReferenceEquals(other, null)) {
            return false;
          }
          if (ReferenceEquals(other, this)) {
            return true;
          }
          if (Uid != other.Uid) return false;
          if (ChampionId != other.ChampionId) return false;
          if (Camp != other.Camp) return false;
          if(!skill_.Equals(other.skill_)) return false;
          return Equals(_unknownFields, other._unknownFields);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public override int GetHashCode() {
          int hash = 1;
          if (Uid != 0) hash ^= Uid.GetHashCode();
          if (ChampionId != 0) hash ^= ChampionId.GetHashCode();
          if (Camp != 0) hash ^= Camp.GetHashCode();
          hash ^= skill_.GetHashCode();
          if (_unknownFields != null) {
            hash ^= _unknownFields.GetHashCode();
          }
          return hash;
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public override string ToString() {
          return pb::JsonFormatter.ToDiagnosticString(this);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public void WriteTo(pb::CodedOutputStream output) {
          if (Uid != 0) {
            output.WriteRawTag(8);
            output.WriteInt32(Uid);
          }
          if (ChampionId != 0) {
            output.WriteRawTag(16);
            output.WriteInt32(ChampionId);
          }
          if (Camp != 0) {
            output.WriteRawTag(24);
            output.WriteInt32(Camp);
          }
          skill_.WriteTo(output, _repeated_skill_codec);
          if (_unknownFields != null) {
            _unknownFields.WriteTo(output);
          }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public int CalculateSize() {
          int size = 0;
          if (Uid != 0) {
            size += 1 + pb::CodedOutputStream.ComputeInt32Size(Uid);
          }
          if (ChampionId != 0) {
            size += 1 + pb::CodedOutputStream.ComputeInt32Size(ChampionId);
          }
          if (Camp != 0) {
            size += 1 + pb::CodedOutputStream.ComputeInt32Size(Camp);
          }
          size += skill_.CalculateSize(_repeated_skill_codec);
          if (_unknownFields != null) {
            size += _unknownFields.CalculateSize();
          }
          return size;
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public void MergeFrom(player_info other) {
          if (other == null) {
            return;
          }
          if (other.Uid != 0) {
            Uid = other.Uid;
          }
          if (other.ChampionId != 0) {
            ChampionId = other.ChampionId;
          }
          if (other.Camp != 0) {
            Camp = other.Camp;
          }
          skill_.Add(other.skill_);
          _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public void MergeFrom(pb::CodedInputStream input) {
          uint tag;
          while ((tag = input.ReadTag()) != 0) {
            switch(tag) {
              default:
                _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
                break;
              case 8: {
                Uid = input.ReadInt32();
                break;
              }
              case 16: {
                ChampionId = input.ReadInt32();
                break;
              }
              case 24: {
                Camp = input.ReadInt32();
                break;
              }
              case 34:
              case 32: {
                skill_.AddEntriesFrom(input, _repeated_skill_codec);
                break;
              }
            }
          }
        }

      }

    }
    #endregion

  }

  #endregion

}

#endregion Designer generated code
