// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: Define/BattleMsg.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Network {

  /// <summary>Holder for reflection information generated from Define/BattleMsg.proto</summary>
  public static partial class BattleMsgReflection {

    #region Descriptor
    /// <summary>File descriptor for Define/BattleMsg.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static BattleMsgReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChZEZWZpbmUvQmF0dGxlTXNnLnByb3RvEgdOZXR3b3JrIjIKEGJhdHRsZV9z",
            "dGFydF9zMmMSEAoIc2VsZl91aWQYASABKAUSDAoEdWlkcxgCIAMoBWIGcHJv",
            "dG8z"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Network.battle_start_s2c), global::Network.battle_start_s2c.Parser, new[]{ "SelfUid", "Uids" }, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  /// <summary>
  /// 战斗开始
  /// </summary>
  public sealed partial class battle_start_s2c : pb::IMessage<battle_start_s2c> {
    private static readonly pb::MessageParser<battle_start_s2c> _parser = new pb::MessageParser<battle_start_s2c>(() => new battle_start_s2c());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<battle_start_s2c> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Network.BattleMsgReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public battle_start_s2c() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public battle_start_s2c(battle_start_s2c other) : this() {
      selfUid_ = other.selfUid_;
      uids_ = other.uids_.Clone();
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public battle_start_s2c Clone() {
      return new battle_start_s2c(this);
    }

    /// <summary>Field number for the "self_uid" field.</summary>
    public const int SelfUidFieldNumber = 1;
    private int selfUid_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int SelfUid {
      get { return selfUid_; }
      set {
        selfUid_ = value;
      }
    }

    /// <summary>Field number for the "uids" field.</summary>
    public const int UidsFieldNumber = 2;
    private static readonly pb::FieldCodec<int> _repeated_uids_codec
        = pb::FieldCodec.ForInt32(18);
    private readonly pbc::RepeatedField<int> uids_ = new pbc::RepeatedField<int>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::RepeatedField<int> Uids {
      get { return uids_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as battle_start_s2c);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(battle_start_s2c other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (SelfUid != other.SelfUid) return false;
      if(!uids_.Equals(other.uids_)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (SelfUid != 0) hash ^= SelfUid.GetHashCode();
      hash ^= uids_.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (SelfUid != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(SelfUid);
      }
      uids_.WriteTo(output, _repeated_uids_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (SelfUid != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(SelfUid);
      }
      size += uids_.CalculateSize(_repeated_uids_codec);
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(battle_start_s2c other) {
      if (other == null) {
        return;
      }
      if (other.SelfUid != 0) {
        SelfUid = other.SelfUid;
      }
      uids_.Add(other.uids_);
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            SelfUid = input.ReadInt32();
            break;
          }
          case 18:
          case 16: {
            uids_.AddEntriesFrom(input, _repeated_uids_codec);
            break;
          }
        }
      }
    }

  }

  #endregion

}

#endregion Designer generated code
