syntax = "proto3";

package Network;

import "Define/BattleMsg.proto";
import "Define/InputMsg.proto";

// 收集操作广播
message frame_start_s2c {
  int32 frame = 1;
}

// 帧操作
message frame_input_c2s {
  int32 frame = 1;
  battle_input input = 2;
  int32 status_code = 3;
}

// 帧操作广播
message frame_input_s2c {
  int32 frame = 1;
  
  message input_info {
    int32 uid = 1;
    battle_input input = 2;
  }
  
  repeated input_info inputs = 2;
}

// 断线重连请求历史帧
message frame_reconnect_c2s {
  int32 frame = 1;
}