syntax = "proto3";

package Network;

import "Define/TypeMsg.proto";

message battle_input {
  test_input test = 1;
  skill_input skill = 2;
  level_input level = 3;
}

message test_input {
  int32 count = 1;
}

message skill_param {
  vector_f pos = 1;
  int32 uid = 2;
}

message skill_info {
  // 0 move 1 attack 2-5 skill 6-11 equipment
  int32 slot = 1;
  skill_param param = 2;
}

message skill_input {
  repeated skill_info info = 1;
}

message skill_level_up_info {
  int32 slot = 1;
}

message level_input {
  repeated skill_level_up_info level_up = 1;
}
